//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigtranNet.Protocols.Transport.Sctp.Packets.Chunks.Parameters.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SigtranNet.Protocols.Transport.Sctp.Packets.Chunks.Parameters.Exceptions.Exceptio" +
                            "nMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Advertised Receiver Window Credit (a_rwnd) is invalid. It must not be smaller than 1500..
        /// </summary>
        internal static string AdvertisedReceiverWindowCreditInvalid {
            get {
                return ResourceManager.GetString("AdvertisedReceiverWindowCreditInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chunk Parameter Length &apos;{1}&apos; is invalid for Chunk Parameter Type &apos;{0}&apos;..
        /// </summary>
        internal static string ChunkParameterLengthInvalid {
            get {
                return ResourceManager.GetString("ChunkParameterLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chunk Parameter Type &apos;{0}&apos; is invalid or not supported..
        /// </summary>
        internal static string ChunkParameterTypeInvalid {
            get {
                return ResourceManager.GetString("ChunkParameterTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Host Name Address is invalid. Must end with at least one NULL terminator..
        /// </summary>
        internal static string HostNameAddressInvalid {
            get {
                return ResourceManager.GetString("HostNameAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Initiate Tag value is invalid. Must be a range of 1 to 2**32 - 1..
        /// </summary>
        internal static string InitiateTagInvalid {
            get {
                return ResourceManager.GetString("InitiateTagInvalid", resourceCulture);
            }
        }
    }
}
